AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Plantilla CloudFormation para AWS CodePipeline y CodeBuild
  para automatizar el pipeline MLOps de Iris usando GitHub como fuente.

Parameters:
  ProjectName:
    Type: String
    Description: Nombre del proyecto para prefijos de recursos.
    Default: iris-mlops

  GitHubConnectionArn:
    Type: String
    Description: El ARN de la conexión de AWS CodeStar para GitHub.
    # *** IMPORTANTE: REEMPLAZA CON EL ARN REAL DE TU CONEXION ***
    Default: arn:aws:codeconnections:us-east-1:503427799533:connection/a21550f1-fb07-4a40-8ffc-198f6f30a8e5 # <--- ¡CAMBIA ESTO CON TU ARN REAL!

  GitHubRepositoryOwner:
    Type: String
    Description: Nombre de usuario o organización de GitHub propietaria del repositorio.
    Default: AlbertStats19

  GitHubRepositoryName:
    Type: String
    Description: Nombre del repositorio de GitHub.
    Default: AWSML

  GitHubBranchName:
    Type: String
    Description: Nombre de la rama en GitHub a monitorear.
    Default: main

Resources:
  # CodeBuild Project para ejecutar el SageMaker Pipeline
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-CodeBuild-Project"
      Description: Proyecto CodeBuild para ejecutar el SageMaker Pipeline de Iris.
      ServiceRole: !ImportValue
        Fn::Sub: "${ProjectName}-CodeBuildServiceRoleArn"
      Artifacts:
        Type: CODEPIPELINE # CodeBuild no necesita subir artefactos a CodePipeline en este caso
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM # O MEDIUM/LARGE segun necesidad
        Image: aws/codebuild/standard:5.0 # Una imagen con Python 3.9
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWS_REGION
            Value: !Ref "AWS::Region"
          - Name: S3_ARTIFACT_BUCKET
            Value: !ImportValue
              Fn::Sub: "${ProjectName}-MLOpsArtifactsBucketName"
          - Name: SAGEMAKER_EXECUTION_ROLE_ARN
            Value: !ImportValue
              Fn::Sub: "${ProjectName}-SageMakerExecutionRoleArn"
          - Name: SAGEMAKER_MODEL_PACKAGE_GROUP_NAME
            Value: !ImportValue
              Fn::Sub: "${ProjectName}-IrisModelPackageGroupName"
          - Name: SAGEMAKER_BASE_JOB_PREFIX
            Value: !Sub "${ProjectName}-pipeline" # Prefijo para trabajos de SageMaker dentro del pipeline
      Source:
        Type: CODEPIPELINE # Se obtiene el código de CodePipeline
        BuildSpec: buildspec.yml # El archivo buildspec.yml en el repo
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # CodePipeline para orquestar el CI/CD
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ProjectName}-MLOps-Pipeline"
      RoleArn: !ImportValue
        Fn::Sub: "${ProjectName}-CodePipelineServiceRoleArn"
      ArtifactStore:
        Type: S3
        Location: !ImportValue
          Fn::Sub: "${ProjectName}-MLOpsArtifactsBucketName"
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection # <-- ¡ESTE ES EL CAMBIO CLAVE!
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Sub "${GitHubRepositoryOwner}/${GitHubRepositoryName}"
                BranchName: !Ref GitHubBranchName
              RunOrder: 1
        - Name: BuildAndTrain
          Actions:
            - Name: BuildAndRunSageMakerPipeline
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
      Tags:
        - Key: Project
          Value: !Ref ProjectName


Outputs:
  CodeBuildProjectName:
    Description: Nombre del proyecto CodeBuild.
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub "${ProjectName}-CodeBuildProjectName"

  CodePipelineName:
    Description: Nombre del CodePipeline.
    Value: !Ref CodePipeline
    Export:
      Name: !Sub "${ProjectName}-CodePipelineName"